<a href="https://colab.research.google.com/github/AniruddhSrivatsa/AniruddhSrivatsa/blob/master/sms_spam_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("spamm.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df["Message"][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [ ]:
df.shape

(5572, 2)

In [ ]:
df.isna().sum()

Category    0
Message     0
dtype: int64

In [ ]:
df["Message"]=df["Message"].str.lower()

In [ ]:
df["Message"]=df["Message"].apply(lambda x: " ".join([info for info in x.split() if info.isalpha() ]))

In [ ]:
df["Message"][0]

'go until jurong available only in bugis n great world la e cine there got amore'

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
df["Message"]=df["Message"].apply(lambda x: " ".join([info for info in x.split() if info not in stopwords.words("english") ]))

In [ ]:
df["Message"][0]

'go jurong available bugis n great world la e cine got amore'

In [ ]:
df["Message"]=df["Message"].apply(lambda x: " ".join([info for info in x.split() if (len(info)!=1) ]))

In [ ]:
df["Message"][1]

'ok joking wif'

In [ ]:
df.head()

Category                                            Message
0      ham  go jurong available bugis great world la cine ...
1      ham                                      ok joking wif
2     spam  free entry wkly comp win fa cup final tkts may...
3      ham                              dun say early already
4      ham                 nah think goes lives around though

In [ ]:
df["Category"]=df["Category"].map({"ham":1,"spam":0})

In [ ]:
df1=pd.get_dummies(df["Category"])

In [ ]:
df.head(10)

Category                                            Message  0  1
0         1  go jurong available bugis great world la cine ...  0  1
1         1                                      ok joking wif  0  1
2         0  free entry wkly comp win fa cup final tkts may...  1  0
3         1                              dun say early already  0  1
4         1                 nah think goes lives around though  0  1
5         0  freemsg hey darling word like fun tb xxx std c...  1  0
6         1            even brother like speak treat like aids  0  1
7         1  per request melle minnaminunginte nurungu set ...  0  1
8         0  valued network customer selected receivea priz...  1  0
9         0  mobile months entitled update latest colour mo...  1  0

In [ ]:
df=pd.concat([df,df1],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df["Message"],df[[0,1]],stratify=df[[0,1]],test_size=0.2,random_state=0)

In [ ]:
X1_train,X1_test,y1_train,y1_test=train_test_split(df["Message"],df["Category"],stratify=df["Category"],test_size=0.2,random_state=0)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
ar=list(X_train.astype("str"))
ar1=list(X_test.astype("str"))

In [ ]:
ar3=list(X1_train.astype("str"))
ar4=list(X1_test.astype("str"))

In [ ]:
tokens=Tokenizer(oov_token="<OOV>")
tokens.fit_on_texts(ar)
word_index=tokens.word_index

In [ ]:
tokens1=Tokenizer(oov_token="<OOV>")
tokens1.fit_on_texts(ar3)
word_index1=tokens.word_index

In [ ]:
print(word_index)

{'<OOV>': 1, 'call': 2, 'ur': 3, 'get': 4, 'go': 5, 'know': 6, 'like': 7, 'come': 8, 'got': 9, 'free': 10, 'send': 11, 'good': 12, 'want': 13, 'ok': 14, 'text': 15, 'going': 16, 'time': 17, 'need': 18, 'love': 19, 'txt': 20, 'still': 21, 'one': 22, 'see': 23, 'dont': 24, 'new': 25, 'think': 26, 'tell': 27, 'back': 28, 'reply': 29, 'mobile': 30, 'stop': 31, 'take': 32, 'home': 33, 'please': 34, 'hope': 35, 'make': 36, 'pls': 37, 'hi': 38, 'day': 39, 'claim': 40, 'phone': 41, 'hey': 42, 'give': 43, 'later': 44, 'much': 45, 'sorry': 46, 'ask': 47, 'da': 48, 'great': 49, 'night': 50, 'meet': 51, 'every': 52, 'happy': 53, 'im': 54, 'dear': 55, 'say': 56, 'well': 57, 'today': 58, 'number': 59, 'would': 60, 'last': 61, 'way': 62, 'oh': 63, 'cos': 64, 'really': 65, 'said': 66, 'find': 67, 'pick': 68, 'miss': 69, 'cash': 70, 'thanks': 71, 'sent': 72, 'even': 73, 'let': 74, 'next': 75, 'right': 76, 'win': 77, 'nokia': 78, 'could': 79, 'work': 80, 'wat': 81, 'also': 82, 'keep': 83, 'contact': 84,

In [ ]:
len(word_index)

5357

In [ ]:
seq=tokens.texts_to_sequences(ar)

In [ ]:
seq1=tokens.texts_to_sequences(ar1)

In [ ]:
seq2=tokens.texts_to_sequences(ar3)
seq3=tokens.texts_to_sequences(ar4)

In [ ]:
pad1=pad_sequences(seq,padding="post",maxlen=38,truncating="post")
pad2=pad_sequences(seq1,padding="post",maxlen=38,truncating="post")

In [ ]:
pad3=pad_sequences(seq2,padding="post",maxlen=38,truncating="post")
pad4=pad_sequences(seq3,padding="post",maxlen=38,truncating="post")

In [ ]:
from tensorflow.keras.utils import to_categorical

0  1
0     0  1
1     0  1
2     1  0
3     0  1
4     0  1
...  .. ..
5567  1  0
5568  0  1
5569  0  1
5570  0  1
5571  0  1

[5572 rows x 2 columns]

In [ ]:
pad1.shape

(4457, 38)

In [ ]:
mess=[len(i) for i in df["Message"]]

In [ ]:
from tensorflow.keras.layers import Dense,Bidirectional,LSTM,Dropout,GlobalAveragePooling1D,Conv1D,Embedding,MaxPooling1D,Flatten
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
callbacks=EarlyStopping(patience=3)

In [ ]:
yk=df["Category"]

In [ ]:
model=Sequential()
model.add(Embedding(input_dim=len(word_index)+1,output_dim=180,input_length=38))
model.add(Conv1D(128,5,activation="relu"))
model.add(Dropout(0.1))
model.add(Bidirectional(LSTM(150)))

model.add(Flatten())
model.add(Dense(2,activation="sigmoid"))

In [ ]:
model1=Sequential()
model1.add(Embedding(input_dim=len(word_index1)+1,output_dim=180,input_length=38))
model1.add(Bidirectional(LSTM(180)))
model1.add(Dense(1,activation="sigmoid"))

In [ ]:
model11=Sequential()
model11.add(Embedding(input_dim=len(word_index)+1,output_dim=160,input_length=38))

model11.add(Bidirectional(LSTM(180)))

model11.add(Dense(1,activation="sigmoid"))

In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model1.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
history=model.fit(pad1,y_train,epochs=10,callbacks=[callbacks],validation_split=0.1)

Epoch 1/10
126/126 [==============================] - 17s 135ms/step - loss: 0.0108 - accuracy: 0.9973 - val_loss: 0.0346 - val_accuracy: 0.9888
Epoch 2/10
126/126 [==============================] - 17s 134ms/step - loss: 0.0054 - accuracy: 0.9990 - val_loss: 0.0397 - val_accuracy: 0.9888
Epoch 3/10
126/126 [==============================] - 17s 134ms/step - loss: 0.0057 - accuracy: 0.9990 - val_loss: 0.0422 - val_accuracy: 0.9910
Epoch 4/10
126/126 [==============================] - 17s 135ms/step - loss: 0.0047 - accuracy: 0.9990 - val_loss: 0.0415 - val_accuracy: 0.9910


In [ ]:
history1=model1.fit(pad3,y1_train,epochs=10,callbacks=[callbacks],validation_split=0.05)

Epoch 1/10
133/133 [==============================] - 26s 192ms/step - loss: 0.1796 - accuracy: 0.9381 - val_loss: 0.0635 - val_accuracy: 0.9776
Epoch 2/10
133/133 [==============================] - 25s 187ms/step - loss: 0.0455 - accuracy: 0.9865 - val_loss: 0.0767 - val_accuracy: 0.9865
Epoch 3/10
133/133 [==============================] - 25s 187ms/step - loss: 0.0222 - accuracy: 0.9953 - val_loss: 0.0746 - val_accuracy: 0.9910
Epoch 4/10
133/133 [==============================] - 25s 187ms/step - loss: 0.0145 - accuracy: 0.9965 - val_loss: 0.0831 - val_accuracy: 0.9910


In [ ]:
model.evaluate(pad2,y_test)

35/35 [==============================] - 1s 26ms/step - loss: 0.1636 - accuracy: 0.9677


[0.16360293328762054, 0.9677129983901978]

In [ ]:
model1.evaluate(pad4,y1_test)

35/35 [==============================] - 2s 53ms/step - loss: 0.0719 - accuracy: 0.9803


[0.07185696810483932, 0.9802690744400024]

In [ ]:
y_pred=model.predict(pad2)

In [ ]:
y_pred1=model1.predict(pad4)

In [ ]:
y_pred1.shape

(1115, 1)

In [ ]:
y_pred1[0]

array([0.9923937], dtype=float32)

In [ ]:
max(y_pred1)

array([0.9999831], dtype=float32)

In [ ]:
elements=["spam","ham"]

In [ ]:
predic=[]

In [ ]:
for i in y_pred1:
  
  predic.append(i)


In [ ]:
print(predic[:20],y1_test[:20])

[array([0.9923937], dtype=float32), array([0.99937284], dtype=float32), array([0.99942434], dtype=float32), array([0.9996253], dtype=float32), array([0.99652934], dtype=float32), array([0.999738], dtype=float32), array([0.99995446], dtype=float32), array([0.0006927], dtype=float32), array([7.5774797e-06], dtype=float32), array([0.9995313], dtype=float32), array([0.99873316], dtype=float32), array([7.848846e-06], dtype=float32), array([0.99972343], dtype=float32), array([0.9999079], dtype=float32), array([0.99997306], dtype=float32), array([2.8045248e-05], dtype=float32), array([0.9989049], dtype=float32), array([2.376028e-05], dtype=float32), array([0.9998294], dtype=float32), array([0.90078133], dtype=float32)] 1589    1
5169    1
365     1
3821    1
714     1
3880    1
2178    1
684     0
4183    0
2982    1
204     1
2767    0
1679    1
299     1
5026    1
824     0
2813    1
1380    0
2177    1
2379    1
Name: Category, dtype: int64


In [ ]:
sent=["ok joking wif","free card won claim it now"]

In [ ]:

see=tokens.texts_to_sequences(sent)
padded=pad_sequences(see,maxlen=38,truncating="post",padding="post")
opp=model1.predict(padded)
print(opp)
for i in opp:
  for j in i:
   print(j)
   if j>0.68:
    print("ham message")
   else:
    print("spam message")



[[9.9983418e-01]
 [6.1258674e-04]]
0.9998342
ham message
0.00061258674
spam message
